mlflow:
  tracking-server: 'dagshub'
  dagshub:
    - repo-owner: 'K14aNB'
    - experiment-name: 'California_Housing_Prices'
    - dotenv-path: '~/.env/California-Housing-Prices/environment_variables.env'

notebooks:
  California-Housing-Prices:
    data:
      - source: 'kaggle-datasets'
      - data-src-path: 'camnugent/california-housing-prices'
    outputs:
      - nb-html-preview: 'true'
      - py-percent-script: 'true'
      - output-path: 'Notebooks'